// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOu7hiklVBLAQgq5m4mvGleF-LFxQsyuQ',
    appId: '1:794429399057:web:4148e0e7e008994f1551b0',
    messagingSenderId: '794429399057',
    projectId: 'adventures-club-12206',
    authDomain: 'adventures-club-12206.firebaseapp.com',
    storageBucket: 'adventures-club-12206.appspot.com',
    measurementId: 'G-JSK4LMF0TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtL9qUOhnLrU5W0G4bYLwuOzlpnPufMyg',
    appId: '1:794429399057:android:366c317e2abc7eaa1551b0',
    messagingSenderId: '794429399057',
    projectId: 'adventures-club-12206',
    storageBucket: 'adventures-club-12206.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjZDRq_ohrbPCPx17t0yf7ozwIJ3wY01o',
    appId: '1:794429399057:ios:5ecbdea69893ee121551b0',
    messagingSenderId: '794429399057',
    projectId: 'adventures-club-12206',
    storageBucket: 'adventures-club-12206.appspot.com',
    iosBundleId: 'com.universalskills.adventuresclub',
  );
}
