// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy8VlgDdWk37VDGEroe1AelRG-A-3yeIM',
    appId: '1:393136578346:web:855dfcf6bd48e8b23f0853',
    messagingSenderId: '393136578346',
    projectId: 'adventuresclub-1d3b7',
    authDomain: 'adventuresclub-1d3b7.firebaseapp.com',
    storageBucket: 'adventuresclub-1d3b7.firebasestorage.app',
    measurementId: 'G-MDJ6D4R97P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7RRpdcJPLsSNQATm9TfPueve-LF29MQE',
    appId: '1:393136578346:android:bd0048b790e3b4dd3f0853',
    messagingSenderId: '393136578346',
    projectId: 'adventuresclub-1d3b7',
    storageBucket: 'adventuresclub-1d3b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_IMg2p3A8bcdDo8Z6YhDcGTSeT0TUjQs',
    appId: '1:393136578346:ios:c3b8ac49284cf9de3f0853',
    messagingSenderId: '393136578346',
    projectId: 'adventuresclub-1d3b7',
    storageBucket: 'adventuresclub-1d3b7.firebasestorage.app',
    iosBundleId: 'com.universalskills.adventuresclub',
  );

}