// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnatsXDV908Li6bGzwnF_AHk1yWM7fHJQ',
    appId: '1:328868209304:web:7126c5cb084ac6854ba6ed',
    messagingSenderId: '328868209304',
    projectId: 'adventuresclub-6b296',
    authDomain: 'adventuresclub-6b296.firebaseapp.com',
    storageBucket: 'adventuresclub-6b296.firebasestorage.app',
    measurementId: 'G-9D3MTD55G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHxPdAapDULhuGBmco9gGkvtRrenhHE3I',
    appId: '1:328868209304:android:8bb6051ddbc8f8ea4ba6ed',
    messagingSenderId: '328868209304',
    projectId: 'adventuresclub-6b296',
    storageBucket: 'adventuresclub-6b296.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdMC9e7qGKO6Elh3_eSmgUK38hlfBs3Sw',
    appId: '1:328868209304:ios:c2585967bfb80ebb4ba6ed',
    messagingSenderId: '328868209304',
    projectId: 'adventuresclub-6b296',
    storageBucket: 'adventuresclub-6b296.firebasestorage.app',
    iosBundleId: 'com.universalskills.adventuresclub',
  );

}